[formatting]
align_entries         = true
column_width          = 120
compact_arrays        = false
reorder_inline_tables = true
reorder_keys          = true

[[rule]]
include = [ "**/pyproject.toml" ]
keys    = [ "project" ]

[rule.formatting]
reorder_keys = false
